# Generated by Django 2.2.5 on 2019-09-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250, unique=True)),
                ('Age', models.IntegerField(default=0)),
                ('Job_Position', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobrestapp.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=250)),
                ('Company', models.CharField(default='', max_length=250)),
                ('Location', models.CharField(default='', max_length=250)),
                ('Job_Description', models.TextField()),
                ('Job_type', models.CharField(choices=[('Full Time', 'Fulltime'), ('Part Time', 'Partimes'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], default='', max_length=65)),
                ('applicants', models.ManyToManyField(through='Jobrestapp.Applications', to='Jobrestapp.Applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='postjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobrestapp.Post_Job'),
        ),
    ]
